insert into customer (name, phone, email, notes) values ('Noby', '304-936-6779', 'nkierans0@fda.gov', 'Pharmacist');
insert into customer (name, phone, email, notes) values ('Rhianna', '896-358-2392', 'rvassall1@dailymail.co.uk', 'Sales Associate');
insert into customer (name, phone, email, notes) values ('Anson', '343-284-1606', 'adellit2@github.com', 'Project Manager');
insert into customer (name, phone, email, notes) values ('Amity', '279-466-3681', 'abedborough3@discovery.com', 'Computer Systems Analyst IV');
insert into customer (name, phone, email, notes) values ('Joachim', '364-186-1344', 'jhedaux4@furl.net', 'Operator');
insert into customer (name, phone, email, notes) values ('Frannie', '353-259-9300', 'fdorrington5@google.nl', 'Safety Technician III');
insert into customer (name, phone, email, notes) values ('Barth', '466-634-5109', 'bpardey6@over-blog.com', 'Project Manager');
insert into customer (name, phone, email, notes) values ('Bryn', '444-353-5624', 'bkinningley7@telegraph.co.uk', 'Quality Control Specialist');
insert into customer (name, phone, email, notes) values ('Cecile', '416-297-5922', 'cliddington8@google.com', 'Clinical Specialist');
insert into customer (name, phone, email, notes) values ('Georgeta', '602-911-3839', 'gchichgar9@cmu.edu', 'Nurse Practicioner');
insert into customer (name, phone, email, notes) values ('Raviv', '834-509-2792', 'rgaita@cargocollective.com', 'General Manager');
insert into customer (name, phone, email, notes) values ('Vida', '884-882-0881', 'vdeminicob@edublogs.org', 'Operator');
insert into customer (name, phone, email, notes) values ('Kat', '943-283-7708', 'kpizzeyc@ifeng.com', 'Help Desk Technician');
insert into customer (name, phone, email, notes) values ('Marissa', '459-781-4450', 'mralstond@github.com', 'Social Worker');
insert into customer (name, phone, email, notes) values ('Oliver', '398-269-6587', 'omallabunde@posterous.com', 'Physical Therapy Assistant');
insert into customer (name, phone, email, notes) values ('Yettie', '571-177-8038', 'ygrinterf@tumblr.com', 'Information Systems Manager');
insert into customer (name, phone, email, notes) values ('Sutton', '122-403-1463', 'sruossg@huffingtonpost.com', 'Assistant Manager');
insert into customer (name, phone, email, notes) values ('Lorraine', '666-884-1064', 'lorsmanh@networkadvertising.org', 'Recruiter');
insert into customer (name, phone, email, notes) values ('Gabriel', '854-528-9054', 'gnellisi@buzzfeed.com', 'Financial Analyst');
insert into customer (name, phone, email, notes) values ('Gal', '811-491-9207', 'gcalbreathj@ycombinator.com', 'VP Sales');
insert into customer (name, phone, email, notes) values ('Lindy', '601-738-9378', 'lduckk@ucsd.edu', 'VP Accounting');
insert into customer (name, phone, email, notes) values ('Nerte', '100-936-5459', 'npurringtonl@goo.gl', 'Data Coordiator');
insert into customer (name, phone, email, notes) values ('Trixi', '925-201-5872', 'tatterburym@businessweek.com', 'Internal Auditor');
insert into customer (name, phone, email, notes) values ('Wendi', '243-732-7736', 'wgobeaun@google.com', 'Analyst Programmer');
insert into customer (name, phone, email, notes) values ('Phyllys', '374-666-8130', 'psprowleso@tinyurl.com', 'Internal Auditor');
insert into customer (name, phone, email, notes) values ('Louise', '586-543-6875', 'lwillettsp@indiatimes.com', 'Payment Adjustment Coordinator');
insert into customer (name, phone, email, notes) values ('Hyacinthie', '270-259-2086', 'hschlagtmansq@amazon.com', 'Technical Writer');
insert into customer (name, phone, email, notes) values ('Willis', '227-989-9690', 'wmccarverr@canalblog.com', 'Operator');
insert into customer (name, phone, email, notes) values ('Devin', '114-732-3103', 'daskhams@simplemachines.org', 'Tax Accountant');
insert into customer (name, phone, email, notes) values ('Athene', '769-252-7416', 'alocht@pinterest.com', 'Senior Developer');
insert into customer (name, phone, email, notes) values ('Lennard', '454-846-9740', 'lravenscraftu@discuz.net', 'Associate Professor');
insert into customer (name, phone, email, notes) values ('Benedicta', '249-459-0092', 'bcheneryv@yandex.ru', 'Occupational Therapist');
insert into customer (name, phone, email, notes) values ('Dmitri', '859-392-0817', 'dpottenw@nymag.com', 'Computer Systems Analyst I');
insert into customer (name, phone, email, notes) values ('Zak', '755-586-8628', 'zcuddihyx@quantcast.com', 'Financial Advisor');
insert into customer (name, phone, email, notes) values ('Aharon', '701-679-0849', 'astephensy@cpanel.net', 'Financial Advisor');
insert into customer (name, phone, email, notes) values ('Eugenie', '444-799-9914', 'elipsonz@biblegateway.com', 'Computer Systems Analyst I');
insert into customer (name, phone, email, notes) values ('Camel', '595-620-2953', 'cyakuntzov10@timesonline.co.uk', 'Research Assistant I');
insert into customer (name, phone, email, notes) values ('Ayn', '781-894-4316', 'anolte11@live.com', 'Social Worker');
insert into customer (name, phone, email, notes) values ('Quintin', '605-944-8219', 'qcovotto12@pagesperso-orange.fr', 'VP Product Management');
insert into customer (name, phone, email, notes) values ('Nikki', '133-384-2594', 'ndiegan13@nifty.com', 'Design Engineer');
insert into customer (name, phone, email, notes) values ('Suzanne', '331-586-8112', 'scuesta14@myspace.com', 'Senior Editor');
insert into customer (name, phone, email, notes) values ('Johannes', '910-196-9963', 'jamery15@techcrunch.com', 'Registered Nurse');
insert into customer (name, phone, email, notes) values ('Jaimie', '469-168-1589', 'jconant16@yelp.com', 'Budget/Accounting Analyst III');
insert into customer (name, phone, email, notes) values ('Kiel', '461-164-6812', 'kflatt17@tuttocitta.it', 'Business Systems Development Analyst');
insert into customer (name, phone, email, notes) values ('Eleanor', '847-855-9735', 'eruffles18@reuters.com', 'Budget/Accounting Analyst II');
insert into customer (name, phone, email, notes) values ('Paddy', '480-587-5308', 'pharkins19@un.org', 'Administrative Assistant IV');
insert into customer (name, phone, email, notes) values ('Cinderella', '228-596-1671', 'cgristhwaite1a@seattletimes.com', 'Developer II');
insert into customer (name, phone, email, notes) values ('Giff', '194-590-6553', 'gbrackstone1b@theglobeandmail.com', 'Pharmacist');
insert into customer (name, phone, email, notes) values ('Ammamaria', '185-635-0114', 'ajosefsen1c@shinystat.com', 'Automation Specialist III');
insert into customer (name, phone, email, notes) values ('Brenden', '687-180-5676', 'bcaris1d@fotki.com', 'Senior Quality Engineer');
insert into customer (name, phone, email, notes) values ('My', '465-395-8939', 'mskeldinge1e@so-net.ne.jp', 'Actuary');
insert into customer (name, phone, email, notes) values ('Tiffy', '623-259-3660', 'tcraigs1f@surveymonkey.com', 'Business Systems Development Analyst');
insert into customer (name, phone, email, notes) values ('Angy', '751-289-7135', 'aharby1g@jugem.jp', 'Paralegal');
insert into customer (name, phone, email, notes) values ('Artemis', '678-413-8259', 'alavers1h@cnbc.com', 'Safety Technician II');
insert into customer (name, phone, email, notes) values ('Honor', '373-660-6917', 'hclayden1i@ca.gov', 'Executive Secretary');
insert into customer (name, phone, email, notes) values ('Sibby', '403-421-1006', 'sgomery1j@github.io', 'Media Manager II');
insert into customer (name, phone, email, notes) values ('Terese', '699-544-0690', 'twavell1k@auda.org.au', 'VP Marketing');
insert into customer (name, phone, email, notes) values ('Micaela', '812-123-5830', 'mfawley1l@163.com', 'Professor');
insert into customer (name, phone, email, notes) values ('Sheffield', '664-574-5749', 'smaclaig1m@issuu.com', 'Programmer Analyst II');
insert into customer (name, phone, email, notes) values ('Hy', '661-522-0878', 'hkirstein1n@mayoclinic.com', 'Business Systems Development Analyst');
insert into customer (name, phone, email, notes) values ('Chantal', '985-252-7469', 'czanicchi1o@hud.gov', 'Financial Analyst');
insert into customer (name, phone, email, notes) values ('Egon', '206-198-4391', 'etraylen1p@over-blog.com', 'Financial Analyst');
insert into customer (name, phone, email, notes) values ('Margery', '554-495-7045', 'msircombe1q@who.int', 'Senior Editor');
insert into customer (name, phone, email, notes) values ('Sigfrid', '539-472-7811', 'sginner1r@sitemeter.com', 'Technical Writer');
insert into customer (name, phone, email, notes) values ('Meryl', '781-491-4935', 'mguirard1s@meetup.com', 'Marketing Manager');
insert into customer (name, phone, email, notes) values ('Susie', '350-907-1967', 'syitzovitz1t@jimdo.com', 'Information Systems Manager');
insert into customer (name, phone, email, notes) values ('Dalia', '571-185-4973', 'drizziello1u@msn.com', 'Librarian');
insert into customer (name, phone, email, notes) values ('Clementine', '536-975-4380', 'crollett1v@sun.com', 'Food Chemist');
insert into customer (name, phone, email, notes) values ('Moina', '419-799-8954', 'mkleinsinger1w@cnet.com', 'Senior Cost Accountant');
insert into customer (name, phone, email, notes) values ('Marilee', '102-981-3229', 'mbotger1x@booking.com', 'Analog Circuit Design manager');
insert into customer (name, phone, email, notes) values ('Murry', '680-418-2434', 'mvannoni1y@vinaora.com', 'Engineer IV');
insert into customer (name, phone, email, notes) values ('Erek', '537-922-9408', 'epawelek1z@webnode.com', 'Director of Sales');
insert into customer (name, phone, email, notes) values ('Tana', '186-779-8371', 'tstrike20@cargocollective.com', 'Account Executive');
insert into customer (name, phone, email, notes) values ('Ailey', '267-367-8758', 'agreenslade21@tripadvisor.com', 'Recruiting Manager');
insert into customer (name, phone, email, notes) values ('Xavier', '453-719-8822', 'xyea22@stumbleupon.com', 'Compensation Analyst');
insert into customer (name, phone, email, notes) values ('Galina', '543-804-5634', 'gtumelty23@wordpress.com', 'Accounting Assistant I');
insert into customer (name, phone, email, notes) values ('Gwennie', '930-962-3282', 'glyle24@nbcnews.com', 'Systems Administrator I');
insert into customer (name, phone, email, notes) values ('Lori', '257-184-9476', 'lbloggett25@deviantart.com', 'Human Resources Assistant III');
insert into customer (name, phone, email, notes) values ('Matthaeus', '771-963-2001', 'mfatkin26@ft.com', 'Geological Engineer');
insert into customer (name, phone, email, notes) values ('Marco', '572-961-1705', 'mlearned27@dell.com', 'Technical Writer');
insert into customer (name, phone, email, notes) values ('Etienne', '573-510-0516', 'ekale28@miibeian.gov.cn', 'Food Chemist');
insert into customer (name, phone, email, notes) values ('Mirabelle', '860-726-1018', 'mtrewin29@theatlantic.com', 'Software Consultant');
insert into customer (name, phone, email, notes) values ('Clovis', '344-610-8195', 'cabate2a@cnn.com', 'Paralegal');
insert into customer (name, phone, email, notes) values ('Corey', '531-789-4835', 'cgiorgielli2b@histats.com', 'Teacher');
insert into customer (name, phone, email, notes) values ('Zorine', '700-378-7667', 'zgascar2c@state.gov', 'Senior Cost Accountant');
insert into customer (name, phone, email, notes) values ('Lyssa', '163-508-9562', 'lsoppitt2d@instagram.com', 'Analog Circuit Design manager');
insert into customer (name, phone, email, notes) values ('Chane', '674-483-1953', 'cwaadenburg2e@smugmug.com', 'Internal Auditor');
insert into customer (name, phone, email, notes) values ('Merle', '265-351-4850', 'mwoodings2f@g.co', 'Data Coordiator');
insert into customer (name, phone, email, notes) values ('Nikolaus', '196-474-6162', 'nhabard2g@cam.ac.uk', 'Environmental Tech');
insert into customer (name, phone, email, notes) values ('Livvyy', '107-736-7527', 'llandon2h@cbslocal.com', 'Account Representative I');
insert into customer (name, phone, email, notes) values ('Denver', '424-794-0776', 'dstacey2i@yale.edu', 'Quality Engineer');
insert into customer (name, phone, email, notes) values ('Annemarie', '125-333-9256', 'atidball2j@usa.gov', 'Information Systems Manager');
insert into customer (name, phone, email, notes) values ('Gillan', '258-658-8963', 'gchaffe2k@ezinearticles.com', 'Systems Administrator IV');
insert into customer (name, phone, email, notes) values ('Lynea', '382-354-3051', 'lmcsherry2l@tamu.edu', 'Nurse Practicioner');
insert into customer (name, phone, email, notes) values ('Barrett', '899-758-2811', 'bgisbye2m@rambler.ru', 'Programmer I');
insert into customer (name, phone, email, notes) values ('Aurore', '415-914-2888', 'ajeffels2n@geocities.com', 'Sales Associate');
insert into customer (name, phone, email, notes) values ('Maury', '158-543-4969', 'mstienham2o@java.com', 'Senior Cost Accountant');
insert into customer (name, phone, email, notes) values ('Eugenius', '927-470-5287', 'ecordery2p@shop-pro.jp', 'Physical Therapy Assistant');
insert into customer (name, phone, email, notes) values ('Suzi', '430-753-1763', 'sstorres2q@cornell.edu', 'Teacher');
insert into customer (name, phone, email, notes) values ('Patti', '598-316-4757', 'pwallege2r@adobe.com', 'Physical Therapy Assistant');
